owner: smartsamagency
repo: upptime

siteConfigs:
  - name: "SMART SAM - #1 Agence Freelance en Algérie"
    url: "https://smartsam.agency"

status-website:
  cname: status.smartsam.agency
  name: État du serveur SMART SAM
  introTitle: "**SMART SAM** - Surveillance de l'état du système"
  introMessage: Nous surveillons nos systèmes 24h/24 et 7j/7 afin de garantir le meilleur service à nos clients.
  theme: light
