owner: smartsamagency
repo: upptime

sites:
  - name: "SMART SAM Agency"
    url: "https://smartsam.agency"

status-website:
  cname: status.smartsam.agency
  name: Etat du serveur SMART SAM
  introTitle: "Surveillance du systeme"
  introMessage: Nous surveillons nos systemes 24h/24.
  theme: light
